<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\IncidentSeverity;
use App\Enums\IncidentStatus;
use App\Enums\OrganizationRole;
use App\Models\Organization;
use App\Models\OrganizationMember;
use App\Models\Service;
use App\Models\User;
use App\Services\Incidents\IncidentService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * Demo data: one account per role, a realistic service catalogue, and ninety
 * days of incident history.
 *
 * The history is generated by driving the real `IncidentService` rather than by
 * inserting rows. That costs a little speed and buys a lot: every seeded
 * incident has a genuine timeline, genuine audit entries, and clocks written by
 * the same code path production uses — so the metrics dashboard shows numbers
 * that are actually consistent with the incidents behind them. Seeders that
 * INSERT directly tend to produce demo data quietly contradicting the
 * application's own invariants, which is worse than no demo data at all.
 */
final class DatabaseSeeder extends Seeder
{
    private const string DEMO_PASSWORD = 'incidentflow';

    public function run(): void
    {
        if (app()->isProduction()) {
            $this->command?->error('Refusing to seed demo accounts in production.');

            return;
        }

        /*
         * Seeding is a one-shot. docker-compose runs `migrate --force && db:seed
         * --force` on every `up`, and api/horizon/scheduler now wait for that
         * command to *succeed* -- so a second `up` against an existing volume
         * aborted the entire stack on a duplicate-key violation before anything
         * started. Demo data already being present is the normal state on a
         * re-run, not a failure. `migrate:fresh --seed` still reseeds, because
         * it drops the tables first and this check then finds nothing.
         */
        if (Organization::query()->exists()) {
            $this->command?->info('Demo data is already present; nothing to seed.');

            return;
        }

        $organization = Organization::query()->create([
            'name' => 'Northwind Logistics',
            'slug' => 'northwind',
            'timezone' => 'UTC',
        ]);

        $people = $this->seedPeople($organization);
        $services = $this->seedServices($organization);

        $this->seedIncidentHistory($organization, $people, $services);

        $this->report($people);
    }

    /** @return array<string, User> */
    private function seedPeople(Organization $organization): array
    {
        $definitions = [
            'admin' => ['Riya Sharma', 'admin@incidentflow.test', OrganizationRole::Administrator],
            'commander' => ['Daniel Okoye', 'commander@incidentflow.test', OrganizationRole::IncidentCommander],
            'responder' => ['Mei Tanaka', 'responder@incidentflow.test', OrganizationRole::Responder],
            'responder2' => ['Luis Ferreira', 'responder2@incidentflow.test', OrganizationRole::Responder],
            'reporter' => ['Ahmed Hassan', 'reporter@incidentflow.test', OrganizationRole::Reporter],
            'viewer' => ['Sofia Rossi', 'viewer@incidentflow.test', OrganizationRole::Viewer],
        ];

        $people = [];

        foreach ($definitions as $key => [$name, $email, $role]) {
            $user = User::query()->create([
                'name' => $name,
                'email' => $email,
                'password' => self::DEMO_PASSWORD,
                'timezone' => 'UTC',
            ]);

            $user->forceFill(['email_verified_at' => now()])->save();

            OrganizationMember::query()->create([
                'organization_id' => $organization->getKey(),
                'user_id' => $user->getKey(),
                'role' => $role,
                'joined_at' => now()->subMonths(6),
            ]);

            $people[$key] = $user;
        }

        return $people;
    }

    /** @return array<string, Service> */
    private function seedServices(Organization $organization): array
    {
        $definitions = [
            'checkout' => ['Checkout API', 1, 'Payments'],
            'tracking' => ['Shipment Tracking', 1, 'Fulfilment'],
            'notifications' => ['Notification Gateway', 2, 'Platform'],
            'warehouse' => ['Warehouse Sync', 2, 'Fulfilment'],
            'reporting' => ['Internal Reporting', 3, 'Data'],
        ];

        $services = [];

        foreach ($definitions as $key => [$name, $tier, $team]) {
            $services[$key] = Service::query()->create([
                'organization_id' => $organization->getKey(),
                'name' => $name,
                'tier' => $tier,
                'owner_team' => $team,
                'description' => "Owned by the {$team} team.",
                'is_active' => true,
            ]);
        }

        return $services;
    }

    /**
     * @param  array<string, User>  $people
     * @param  array<string, Service>  $services
     */
    private function seedIncidentHistory(Organization $organization, array $people, array $services): void
    {
        $incidents = app(IncidentService::class);

        /**
         * [days ago, severity, service key, title, minutes to acknowledge,
         * minutes to resolve — or null to leave it running]
         *
         * Deliberately uneven: a couple of genuinely slow responses so p95
         * differs visibly from the mean, and three still-open incidents so the
         * dashboard has something live to show.
         */
        $script = [
            [88, IncidentSeverity::Sev1, 'checkout', 'Checkout API returning 500s for all customers', 3, 94],
            [81, IncidentSeverity::Sev2, 'tracking', 'Shipment tracking pages timing out', 22, 180],
            [74, IncidentSeverity::Sev3, 'reporting', 'Nightly reporting job failed to complete', 210, 400],
            [66, IncidentSeverity::Sev1, 'checkout', 'Payment provider webhook backlog', 4, 51],
            [59, IncidentSeverity::Sev2, 'notifications', 'Delivery notification emails delayed by 40 minutes', 12, 145],
            [52, IncidentSeverity::Sev4, 'reporting', 'Dashboard chart legend rendering incorrectly', 480, 1_200],
            [45, IncidentSeverity::Sev2, 'warehouse', 'Warehouse stock sync drifting for the EU region', 18, 620],
            [38, IncidentSeverity::Sev3, 'tracking', 'Tracking numbers duplicated for split shipments', 55, 300],
            [31, IncidentSeverity::Sev1, 'checkout', 'Database connection pool exhausted during a flash sale', 2, 38],
            [24, IncidentSeverity::Sev2, 'notifications', 'SMS provider rate limiting our traffic', 9, 210],
            [17, IncidentSeverity::Sev3, 'warehouse', 'Barcode scanner integration dropping events', 40, 260],
            [12, IncidentSeverity::Sev2, 'checkout', 'Elevated latency on the payment authorisation endpoint', 7, 96],
            [8, IncidentSeverity::Sev4, 'reporting', 'CSV export missing the header row', 300, 900],
            [5, IncidentSeverity::Sev1, 'tracking', 'Tracking API unavailable in the APAC region', 5, 72],
            [3, IncidentSeverity::Sev2, 'warehouse', 'Inventory counts stale for three distribution centres', 14, null],
            [1, IncidentSeverity::Sev3, 'notifications', 'Push notifications not delivered on Android 15', 35, null],
            [0, IncidentSeverity::Sev1, 'checkout', 'Card payments failing for a subset of BINs', 4, null],
        ];

        /**
         * The anchor is captured once, before any time travel.
         *
         * Each incident is written with `Carbon::setTestNow()` so its
         * timestamps land in the past, which means `Carbon::now()` inside the
         * loop is whatever the *previous* iteration last set. Deriving
         * "days ago" from that would push each incident further back than the
         * one before it, and ninety days of history would silently spread over
         * several years.
         */
        $anchor = Carbon::now();

        foreach ($script as [$daysAgo, $severity, $serviceKey, $title, $ackMinutes, $resolveMinutes]) {
            $openedAt = $anchor->copy()->subDays($daysAgo)->setTime(random_int(6, 21), random_int(0, 59));

            Carbon::setTestNow($openedAt);

            $incident = $incidents->create($organization, $people['reporter'], [
                'title' => $title,
                'description' => $this->describe($title),
                'impact' => $severity->requiresImmediateNotification()
                    ? 'Customer-facing functionality is degraded.'
                    : 'Limited internal impact; a workaround is available.',
                'severity' => $severity,
                'service_id' => $services[$serviceKey]->getKey(),
            ]);

            Carbon::setTestNow($openedAt->copy()->addMinutes($ackMinutes));
            $incident = $incidents->transition(
                $incident,
                $people['responder'],
                IncidentStatus::Acknowledged,
                'Investigating. Paging the owning team.',
            );

            if ($severity->requiresImmediateNotification()) {
                $incident = $incidents->setCommander($incident, $people['admin'], $people['commander']);
                $incidents->assign($incident, $people['commander'], $people['responder2']);
            }

            if ($resolveMinutes === null) {
                // Still burning — gives the dashboard live incidents to show.
                continue;
            }

            Carbon::setTestNow($openedAt->copy()->addMinutes((int) round($resolveMinutes * 0.6)));
            $incident = $incidents->transition(
                $incident,
                $people['responder'],
                IncidentStatus::Mitigated,
                'Mitigation applied; monitoring for recurrence.',
                publicUpdate: true,
            );

            Carbon::setTestNow($openedAt->copy()->addMinutes($resolveMinutes));
            $incident = $incidents->transition(
                $incident,
                $people['commander'],
                IncidentStatus::Resolved,
                'Root cause addressed and verified in production.',
                publicUpdate: true,
            );

            $incidents->comment(
                $incident,
                $people['responder2'],
                'Adding the dashboards we used during the response, for the postmortem.',
            );

            // Older resolved incidents get closed; recent ones stay open for
            // review, which is what a real queue actually looks like.
            if ($daysAgo > 21) {
                Carbon::setTestNow($openedAt->copy()->addMinutes($resolveMinutes + 240));
                $incidents->transition($incident, $people['commander'], IncidentStatus::Closed);
            }
        }

        Carbon::setTestNow();
    }

    private function describe(string $title): string
    {
        return $title."\n\n".
            'Detected by automated alerting. Initial triage pointed at the most recent deployment; '.
            'the on-call responder began investigating immediately and posted updates as the picture became clearer.';
    }

    /** @param array<string, User> $people */
    private function report(array $people): void
    {
        $this->command?->newLine();
        $this->command?->info('Demo accounts seeded. Password for all of them: '.self::DEMO_PASSWORD);
        $this->command?->table(
            ['Role', 'Email'],
            collect($people)->map(fn (User $user): array => [
                $user->memberships()->first()?->role->label() ?? '—',
                $user->email,
            ])->values()->all(),
        );

        $this->command?->newLine();
        $this->command?->comment(sprintf(
            '%d incidents across 90 days, %d still open.',
            DB::table('incidents')->count(),
            DB::table('incidents')->whereIn('status', IncidentStatus::activeValues())->count(),
        ));
    }
}
